export type HexTableProperty =
  | "FF"
  | "FC"
  | "FA"
  | "F7"
  | "F5"
  | "F2"
  | "F0"
  | "ED"
  | "EB"
  | "E8"
  | "E6"
  | "E3"
  | "E0"
  | "DE"
  | "DB"
  | "D9"
  | "D6"
  | "D4"
  | "D1"
  | "CF"
  | "CC"
  | "C9"
  | "C7"
  | "C4"
  | "C2"
  | "BF"
  | "BD"
  | "BA"
  | "B8"
  | "B5"
  | "B3"
  | "B0"
  | "AD"
  | "AB"
  | "A8"
  | "A6"
  | "A3"
  | "A1"
  | "9E"
  | "9C"
  | "99"
  | "96"
  | "94"
  | "91"
  | "8F"
  | "8C"
  | "8A"
  | "87"
  | "85"
  | "82"
  | "80"
  | "7D"
  | "7A"
  | "78"
  | "75"
  | "73"
  | "70"
  | "6E"
  | "6B"
  | "69"
  | "66"
  | "63"
  | "61"
  | "5E"
  | "5C"
  | "59"
  | "57"
  | "54"
  | "52"
  | "4F"
  | "4D"
  | "4A"
  | "47"
  | "45"
  | "42"
  | "40"
  | "3D"
  | "3B"
  | "38"
  | "36"
  | "33"
  | "30"
  | "2E"
  | "2B"
  | "29"
  | "26"
  | "24"
  | "21"
  | "1F"
  | "1C"
  | "1A"
  | "17"
  | "14"
  | "12"
  | "0F"
  | "0D"
  | "0A"
  | "08"
  | "05"
  | "03"
  | "00";

export interface HexTable {
  "100": HexTableProperty;
  "99": HexTableProperty;
  "98": HexTableProperty;
  "97": HexTableProperty;
  "96": HexTableProperty;
  "95": HexTableProperty;
  "94": HexTableProperty;
  "93": HexTableProperty;
  "92": HexTableProperty;
  "91": HexTableProperty;
  "90": HexTableProperty;
  "89": HexTableProperty;
  "88": HexTableProperty;
  "87": HexTableProperty;
  "86": HexTableProperty;
  "85": HexTableProperty;
  "84": HexTableProperty;
  "83": HexTableProperty;
  "82": HexTableProperty;
  "81": HexTableProperty;
  "80": HexTableProperty;
  "79": HexTableProperty;
  "78": HexTableProperty;
  "77": HexTableProperty;
  "76": HexTableProperty;
  "75": HexTableProperty;
  "74": HexTableProperty;
  "73": HexTableProperty;
  "72": HexTableProperty;
  "71": HexTableProperty;
  "70": HexTableProperty;
  "69": HexTableProperty;
  "68": HexTableProperty;
  "67": HexTableProperty;
  "66": HexTableProperty;
  "65": HexTableProperty;
  "64": HexTableProperty;
  "63": HexTableProperty;
  "62": HexTableProperty;
  "61": HexTableProperty;
  "60": HexTableProperty;
  "59": HexTableProperty;
  "58": HexTableProperty;
  "57": HexTableProperty;
  "56": HexTableProperty;
  "55": HexTableProperty;
  "54": HexTableProperty;
  "53": HexTableProperty;
  "52": HexTableProperty;
  "51": HexTableProperty;
  "50": HexTableProperty;
  "49": HexTableProperty;
  "48": HexTableProperty;
  "47": HexTableProperty;
  "46": HexTableProperty;
  "45": HexTableProperty;
  "44": HexTableProperty;
  "43": HexTableProperty;
  "42": HexTableProperty;
  "41": HexTableProperty;
  "40": HexTableProperty;
  "39": HexTableProperty;
  "38": HexTableProperty;
  "37": HexTableProperty;
  "36": HexTableProperty;
  "35": HexTableProperty;
  "34": HexTableProperty;
  "33": HexTableProperty;
  "32": HexTableProperty;
  "31": HexTableProperty;
  "30": HexTableProperty;
  "29": HexTableProperty;
  "28": HexTableProperty;
  "27": HexTableProperty;
  "26": HexTableProperty;
  "25": HexTableProperty;
  "24": HexTableProperty;
  "23": HexTableProperty;
  "22": HexTableProperty;
  "21": HexTableProperty;
  "20": HexTableProperty;
  "19": HexTableProperty;
  "18": HexTableProperty;
  "17": HexTableProperty;
  "16": HexTableProperty;
  "15": HexTableProperty;
  "14": HexTableProperty;
  "13": HexTableProperty;
  "12": HexTableProperty;
  "11": HexTableProperty;
  "10": HexTableProperty;
  "9": HexTableProperty;
  "8": HexTableProperty;
  "7": HexTableProperty;
  "6": HexTableProperty;
  "5": HexTableProperty;
  "4": HexTableProperty;
  "3": HexTableProperty;
  "2": HexTableProperty;
  "1": HexTableProperty;
  "0": HexTableProperty;
}
